### PR TITLE
Misc. Windows code cleanup

### LINKED ISSUE #582: [windows] Fix plugin exception warnings
Since the change to turn off exceptions in the plugins and runners (to simplify using /clr), the build shows warnings like:
```
[ +732 ms] c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xlocale(319): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\projects\flutter-desktop-embedding\plugins\example_plugin\windows\example_plugin.vcxproj]
```

We should figure out what is using exception handlers, and remove them (or if we can't for some reason, re-evaluate that change).

### LINKED ISSUE #662: Clean up Windows style
The Windows code hasn't been consistent about following Google's style recommendations on Windows code. Notably:
- We shouldn't ever be using Hungarian notation for variable names.
- Pointer types shouldn't use the composite Windows types (e.g., `LP...`).

### PR DESCRIPTION
**Pull request by stuartmorgan**
This is a complete pass over all the code and projects, making a variety of changes:
- Updating style to better match Google style for Windows code (e.g., avoiding LP* types)
- Increasing the warning level for everything from W3 to W4
- Enabling warnings as errors (WX)
- Fixing all warnings
  - Including correctly disabling exceptions in STL via a Define
- clang-formatted some missed files

Fixes #662 
Fixes #582 
Addresses Windows portion of #343

### CODE REVIEW

File: testbed/windows/win32_window.cc [hunk 1]
```diff
@@ -13,14 +13,24 @@ namespace {
...
 // scale factor
 int Scale(int source, double scale_factor) {
   return static_cast<int>(source * scale_factor);
 }
 
+// Returns the DPI for the monitor containing, or closest to, |point|.
+UINT GetDpiForMonitorAtPoint(const Win32Window::Point &point) {
+  const POINT target_point = {static_cast<LONG>(point.x),
+                              static_cast<LONG>(point.y)};
+  HMONITOR monitor = MonitorFromPoint(target_point, MONITOR_DEFAULTTONEAREST);
```
Comment (stuartmorgan) [inline testbed/windows/win32_window.cc]: The reason for this change is that when I was fixing warnings I discovered that passing a null `HWND` to `MonitorFromWindow` is actually a violation of the annotations on the method. The recommended way to get the primary monitor is to call this with a 0,0 point rather than using MonitorFromWindow with null. We should fix that in the embedding.

**Comment by stuartmorgan** [comment]
Looks like I didn't correctly disable the unused parameter warning; I'm not sure why it worked locally. I'll have to fix that next week.
